[package]
name = "rustic"
version = "0.1.0"
edition = "2021"
authors = ["Isak Nyberg <isak@nyberg.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.2"
